version: "3.8"

networks:
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.40.1.0/24"

  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.40.2.0/24"

services:
  # front-proxy:
  #   image: manji955/front-proxy:latest
  #   container_name: docker-front-proxy
  #   networks:
  #     - front_net
  #   restart: always
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  
  # frontend:
  #   image: nextjs:1.0
  #   networks:
  #     - front_net
  #   restart: always
  #   ports:
  #    - "3001-3003:5555"
  #   deploy:
  #     replicas: 3
  #     mode: replicated
  #   depends_on:
  #     - back-proxy

  # back-proxy:
  #   image: manji955/back-proxy:latest
  #   container_name: docker-back-proxy
  #   networks:
  #     - front_net
  #     - back_net
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - backend
    
  backend:
    image: seonxx/docker-flask:latest
    networks:
      - back_net
    restart: always
    ports:
      - "5001-5003:5000"
    deploy:
      replicas: 3
      mode: replicated
    depends_on:
      database:
        condition: service_healthy
    environment:
      - MYSQL_HOST=database
    
  database:
    image: kijung2/docker-mysql:latest
    container_name: docker-mysql
    networks:
      - back_net
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p", "docker"]
      timeout: 20s
      retries: 10