networks:
  front:
    driver: overlay
    ipam:
      config:
        - subnet: "172.30.1.0/24"

  back:
    driver: overlay
    ipam:
      config:
        - subnet: "172.30.2.0/24"

services:
  front-proxy:
    image: manji955/front-proxy
    # command: ["sh", "-c", "./node_exporter/node_exporter"]
    networks:
      - front
    ports:
      - "80:80"
      - "9100:9100"

  frontend:
    image: dbgurum/guestbook:frontend_1.0
    networks:
      - front
    ports:
      - "3001-3003:80"
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints:
          - node.role == worker
    environment:
      - GUESTBOOK_API_ADDR=back-proxy:8080
      - PORT=80

  back-proxy:
    image: manji955/back-proxy
    networks:
      - back
      - front
    ports:
      - "8080:8080"

  backend:
    image: dbgurum/guestbook:backend_1.0
    networks:
      - back
    ports:
      - "5001-5003:8000"
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints:
          - node.role == worker
    environment:
      - PORT=8000
      - GUESTBOOK_DB_ADDR=db:27017

  db:
    image: mongo:4
    networks:
      - back
    ports:
      - "17017:27017"
