networks:
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.40.1.0/24"

  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.40.2.0/24"

services:
  front-proxy:
    image: kijung2/docker-compose-nginx:latest
    container_name: docker-nginx
    networks:
      - front_net
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
  
  frontend:
    image: kijung2/docker-nextjs:latest
    networks:
      - front_net
    restart: always
    deploy:
      replicas: 3
      mode: replicated
    depends_on:
      - back-proxy

  back-proxy:
    image: kijung2/docker-compose-haproxy:latest
    container_name: docker-haproxy
    networks:
      - front_net
      - back_net
    restart: always
    depends_on:
      - backend
    
  backend:
    image: seonxx/docker-flask:latest
    networks:
      - back_net
    restart: always
    deploy:
      replicas: 3
      mode: replicated
    depends_on:
      - database
    environment:
      - MYSQL_HOST=database
    
  database:
    image: kijung2/docker-mysql:latest
    container_name: docker-db
    networks:
      - back_net
    restart: always