networks:
  front_net:
    driver: overlay
    ipam:
      config:
        - subnet: "172.30.1.0/24"

  back_net:
    driver: overlay
    ipam:
      config:
        - subnet: "172.30.2.0/24"

services:
  front-proxy:
    image: kijung2/test-nginx-proxy:1.0
    # command: ["sh", "-c", "./node_exporter/node_exporter"]
    networks:
      - front_net
    ports:
      - "80:80"
      - "9100:9100"

  frontend:
    image: kijung2/frontend-test:1.0
    networks:
      - front_net
    deploy:
      replicas: 3
      mode: replicated
      placement:
        constraints:
          - node.role == worker

  back-proxy:
    image: kijung2/haproxy-test:1.0
    networks:
      - back_net
      - front_net
    ports:
      - "8080:8080"

  backend:
    image: kijung2/docker-flask:latest
    networks:
      - back_net
    deploy:
      replicas: 3
      mode: replicated
      placement:
        constraints:
          - node.role == worker
    environment:
      - MYSQL_HOST=database

  database:
    image: kijung2/docker-mysql:latest
    networks:
      - back_net
