FROM python:3.10.0-alpine

RUN apk update --no-cache && apk add --no-cache bash

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

CMD ["python", "app.py"]
